"""Aggregate-only summary of the quality reports that built a warehouse, for committing next to the code.

    uv run python -m data_engineering.pipelines.load_summary data/reports/quality_A.json data/reports/quality_B.json \
        --out data_engineering/reports/organizer_load.md

The quality reports stay git-ignored under data/reports (they carry local paths and value profiles). This summary
keeps counts and timings only: per run, what each table read, quarantined and holds in silver, and for the warehouse
as a whole, which run last loaded each table. Pass the reports oldest first.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def _minutes(report: dict) -> float:
    started, finished = (datetime.fromisoformat(report[k]) for k in ("started_at", "finished_at"))
    return round((finished - started).total_seconds() / 60, 1)


def _warnings(section: dict) -> int:
    return sum(section.get("warnings_by_reason", {}).values())


def _run_block(report: dict) -> list[str]:
    kind = "full refresh" if report["full_refresh"] else "incremental"
    lines = [f"### Run `{report['run_id']}`", "",
             f"{kind.capitalize()}, {report['source_kind']} source, started {report['started_at'][:19]} UTC, "
             f"{_minutes(report)} minutes.", "",
             "| table | files | rows read | quarantined | exact duplicates | warnings | silver rows after |",
             "|---|---|---|---|---|---|---|"]
    for name, sec in report["tables"].items():
        f, r = sec["files"], sec["rows"]
        if not f["discovered"]:
            lines.append(f"| {name} | 0 (none in the source then) | - | - | - | - | {r['silver_total']:,} |")
            continue
        lines.append(f"| {name} | {f['discovered']:,} | {r['bronze_in']:,} | {r['quarantined']:,} | "
                     f"{r['exact_duplicates']:,} | {_warnings(sec):,} | {r['silver_total']:,} |")
    t = report["totals"]
    lines += ["", f"Totals: {t['bronze_in']:,} rows read, {t['quarantined']:,} quarantined.", ""]
    return lines


def render(reports: list[dict]) -> str:
    labels = {r.get("source_label") for r in reports}
    if any(labels):
        raise ValueError("these reports come from the synthetic fixture; the summary is for organizer data")
    latest: dict[str, tuple[str, dict]] = {}
    for report in reports:
        for name, sec in report["tables"].items():
            if sec["files"]["discovered"]:
                latest[name] = (report["run_id"], sec)
    lines = ["# Organizer data load: aggregate summary", "",
             "Generated by `uv run python -m data_engineering.pipelines.load_summary` from the git-ignored quality "
             "reports of the runs below. Organizer data, counts only.", "",
             "## Warehouse as loaded", "",
             "| table | loaded by run | rows read | quarantined | silver rows |", "|---|---|---|---|---|"]
    for name, (run_id, sec) in sorted(latest.items()):
        r = sec["rows"]
        lines.append(f"| {name} | `{run_id}` | {r['bronze_in']:,} | {r['quarantined']:,} | {r['silver_total']:,} |")
    rows_in = sum(sec["rows"]["bronze_in"] for _, sec in latest.values())
    quarantined = sum(sec["rows"]["quarantined"] for _, sec in latest.values())
    silver = sum(sec["rows"]["silver_total"] for _, sec in latest.values())
    lines += ["", f"{len(latest)} tables, {rows_in:,} rows read by the runs that loaded them, {quarantined:,} "
                  f"quarantined, {silver:,} rows in silver.", "", "## Runs", ""]
    for report in reports:
        lines += _run_block(report)
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("reports", nargs="+", type=Path, help="quality_<run_id>.json files, oldest first")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        text = render([json.loads(p.read_text(encoding="utf-8")) for p in args.reports])
    except ValueError as exc:
        print(f"load summary failed: {exc}", file=sys.stderr)
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
