"""Write ml/DATASHEET.md from the committed case files and manifest.

    uv run python -m ml.scenarios.datasheet

Every count in the datasheet is computed here from eval/cases/disputes/*.jsonl.
"""

from __future__ import annotations

import json
import statistics
from collections import Counter
from pathlib import Path

from ml.data import CASES_DIR, load_cases

SPLITS = ("train", "val", "test")
OUT = Path("ml/DATASHEET.md")


def _table(rows: dict[str, dict[str, int]], cols: list[str], first: str) -> str:
    head = f"| {first} | " + " | ".join(cols) + " | total |\n|" + "---|" * (len(cols) + 2) + "\n"
    body = ""
    for key in sorted(rows):
        vals = [rows[key].get(c, 0) for c in cols]
        body += f"| {key} | " + " | ".join(str(v) for v in vals) + f" | {sum(vals)} |\n"
    return head + body


def _by(cases_by_split: dict, key) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for split, cases in cases_by_split.items():
        for c in cases:
            k = key(c)
            out.setdefault(str(k), {}).setdefault(split, 0)
            out[str(k)][split] += 1
    return out


def render() -> str:
    cases = {s: load_cases(s) for s in SPLITS}
    manifest = json.loads((CASES_DIR / "manifest.json").read_text(encoding="utf-8"))
    pools = {s: [len(c["candidates"]) for c in cases[s]] for s in SPLITS}
    es_only = {s: [c for c in cases[s] if c["language"] == "es"] for s in SPLITS}
    amb = {s: Counter((c["ambiguity_kind"], len(c["consistent_ids"])) for c in cases[s] if c["label"] == "ambiguous")
           for s in SPLITS}
    parts = [HEADER.format(version=manifest["data_version"], fingerprint=manifest["source_fingerprint"],
                           customers=manifest["customers_loaded"],
                           rows=manifest["load_stats"]["rows_kept"], seed=manifest["config"]["seed"])]
    parts.append("## Counts\n\nAll cases (Spanish and Portuguese), by split.\n\n")
    parts.append(_table(_by(cases, lambda c: f"{c['label']} / {c['language']}"), list(SPLITS), "label / language"))
    parts.append("\nBy country and segment (all languages).\n\n")
    parts.append(_table(_by(cases, lambda c: f"{c['country']} / {c['segment']}"), list(SPLITS), "country / segment"))
    parts.append("\nBy template family. F5 and F6 are held out: they exist only in test.\n\n")
    parts.append(_table(_by(cases, lambda c: c["family"]), list(SPLITS), "family"))
    parts.append("\nBy information level (how many cues the description carries).\n\n")
    parts.append(_table(_by(cases, lambda c: f"{c['label']} / {c['info_level']}"), list(SPLITS), "label / level"))
    parts.append("\nMatch cases with one misremembered cue (recall errors), and no-match construction.\n\n")
    parts.append(_table(_by({s: [c for c in cases[s] if c["label"] == "match"] for s in SPLITS},
                            lambda c: c["recall_error"] or "none"), list(SPLITS), "recall error"))
    parts.append("\n")
    parts.append(_table(_by({s: [c for c in cases[s] if c["label"] == "no_match"] for s in SPLITS},
                            lambda c: c["no_match_kind"]), list(SPLITS), "no-match kind"))
    parts.append("\nAmbiguous cases: kind and number of consistent candidates.\n\n| split | kind | consistent | cases |\n|---|---|---|---|\n")
    for s in SPLITS:
        for (kind, n), cnt in sorted(amb[s].items()):
            parts.append(f"| {s} | {kind} | {n} | {cnt} |\n")
    parts.append("\nCandidate pool size (transactions in the 90-day window).\n\n| split | min | median | p90 | max |\n|---|---|---|---|---|\n")
    for s in SPLITS:
        p = sorted(pools[s])
        parts.append(f"| {s} | {p[0]} | {statistics.median(p):g} | {p[int(0.9 * (len(p) - 1))]} | {p[-1]} |\n")
    parts.append("\nCustomers skipped because the requested label could not be built from their transactions "
                 "(Spanish source cases only; each skip moves to the next customer of the same stratum).\n\n")
    parts.append(_table({s: manifest["skipped_customers"][s] for s in SPLITS},
                        ["match", "ambiguous", "no_match"], "split"))
    parts.append(f"\nSpanish source cases per split: "
                 + ", ".join(f"{s} {len(es_only[s])}" for s in SPLITS) + ".\n")
    parts.append(FOOTER)
    return "".join(parts)


HEADER = """# Datasheet: "which charge?" dispute scenarios

Generated by `ml/scenarios/datasheet.py` from `eval/cases/disputes/*.jsonl`. Data version `{version}`,
source fingerprint `{fingerprint}`, builder seed {seed}. Built from {rows} organizer transactions of
{customers} customers.

## What this dataset is

Each case is a customer who says a charge on their account is not theirs, in their own words, plus the
list of that customer's own transactions in the 90 days before the conversation ("report date"). The
task is to point at the charge they mean, ask them to pick when several fit, or stop when none fits.

| Part of a case | Origin |
|---|---|
| Candidate transactions, amounts, dates, merchants, channels, cities | **Organizer data** (synthetic), unchanged |
| Customer country and segment | **Organizer data** (`customers.csv`) |
| Report date, target choice, hints, noise | **Team-generated**, seeded and deterministic |
| Spanish description text | **Team-generated** from templates |
| Portuguese (pt-BR) description text | **TEAM-GENERATED** rendering of the same hints; no organizer text is Portuguese |

The organizer text data (transcripts, complaint descriptions) was not used: it is templated (546 distinct
transcripts over 171k rows, 42 distinct customer utterances, unfilled placeholders, topic labels that do
not match the text), so it cannot supply valid relevance labels for this task. Complaints also carry no
`transaction_id`, which is why this matching is needed at all.

## How labels are made (valid by construction)

A description is rendered from a set of structured hints about one transaction: an approximate amount,
a relative date phrase, the merchant (exact, partial, misspelled, or a noun such as "una farmacia"), the
type, the channel, sometimes the city. The label is a function of the hints and the pool only:

* **consistent** candidate: an approved or pending debit that satisfies every hint within fixed tolerances (amount within a
  factor 1.25 of the claimed value and in the stated currency, date inside the phrase's range +- 2 days,
  merchant compatible with the surface form, type, channel and city equal);
* **near-consistent**: fails exactly one hint of a description with three or more hints;
* `match`: exactly one consistent candidate (the target), or, for recall-error cases, none consistent and
  exactly one near-consistent (the target, with one detail misremembered on purpose);
* `ambiguous`: two or more consistent candidates, the target among them. Correct handling is to clarify;
* `no_match`: no consistent and no near-consistent candidate (the hints describe a perturbed copy of one
  of the customer's transactions, or a transaction of another customer). Correct handling is to abstain.

Because the labeling rule is explicit, a label can be recomputed and audited for any case (`hints` and
`consistent_ids` are stored with each case). Rankers never see the hints, only the text.

"""

FOOTER = """
## Splits and leakage controls

* **Group split by customer**: a salted hash assigns each customer to train (60%), val (20%) or test (20%).
  No customer, and therefore no transaction, appears in two splits (tested).
* **Time split**: report dates fall in 2023-10-01..2025-06-30 (train), 2025-07-01..2025-12-31 (val) and
  2026-01-01..2026-06-17 (test).
* **Held-out template families**: F5 (formal letter) and F6 (oral, regional slang, number words) appear only
  in test. The ranker lexicon and parser were written from F1-F4 only.
* **Portuguese stays with its source**: a pt-BR case copies its Spanish source's split, customer, pool and
  label, and shares its bootstrap group.
* Stratified sampling by country and segment with a per-stratum floor so small strata (Student, Premium,
  Argentina) have enough cases to report.

## Known risks and limitations

* **A model can learn the generator.** Labels come from an explicit rule over hints, so a system that
  mirrors the rule scores well on seen phrasing. Held-out families (F5, F6) and recall-error cases are the
  mitigation; results are reported separately for seen and held-out families.
* **Pools are small.** The organizer data has roughly one transaction per customer per month (median 29
  per customer over three years in the raw files), so 90-day pools are short (see the pool size table);
  top-3 recall is trivially 1 for a pool of 3, which is why results also report it on pools of 4 or more.
* **Selection bias.** Customers need at least 3 transactions in the window and a label that can be built
  from their history; skipped customers are counted above. Active customers are over-represented.
* **Synthetic source data.** Transaction type, channel and merchant are combined at random in the organizer
  data (for example withdrawals "por la app"), so some descriptions read oddly. Mexican customers
  transact mostly in USD in this data; descriptions follow the transaction currency.
* **Portuguese is a rendering, not a translation reviewed by native speakers,** and Brazil does not
  appear in the customer base.
* **Tolerances are team choices** (factor 1.25 on amounts, 2 days of date slack). Other choices would
  move cases between labels.
"""


def main() -> None:
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
